name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore ./src/ServiceStack.OrmLite.sln
    - name: Build
      run: dotnet build ./src/ServiceStack.OrmLite.sln --no-restore
    - name: Test
      run: dotnet test ./src/ServiceStack.OrmLite.sln --no-build --verbosity normal
